admin:
    resource: ../src/Controller/AdminController.php
    type: annotation

book:
    resource: ../src/Controller/BookController.php
    type: annotation

movie:
    resource: ../src/Controller/MovieController.php
    type: annotation